# Data Cleaning

## importing pandas library to read the csv file and perform data cleaning operations

In [42]:
import pandas as pd  #importing pandas library to read the csv file and perform data cleaning operations

# Load the dataset
# Display the first few rows of the dataset

In [43]:
df = pd.read_csv(r"C:\Users\User\OneDrive\Desktop\This Trimester\AI Laboratory\Data cleaning\Customer_Call_List.csv")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

# Droping the duplicates

In [44]:
df=df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

# Droping unnecessary column "Not_Useful_column"

In [45]:
df=df.drop(columns="Not_Useful_Column")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

# Strip

### Cleaning the ""Last_Name"" Columns removing any Unnecessar thing...

In [46]:
# df["Last_Name"] = df["Last_Name"].str.lstrip("...")
# df["Last_Name"] = df["Last_Name"].str.lstrip("/")
# df["Last_Name"] = df["Last_Name"].str.rstrip("_")
# df

df["Last_Name"] = df["Last_Name"].str.strip("123.../_")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

# cleaning/standardizing phone number

In [69]:
# df["Phone_Number"] = df["Phone_Number"].str.replace('[^a-zA-Z0-9]','',regex=True)
# df["Phone_Number"].apply(lambda x: x[0:3] + "-" + x[3:6] + "-" + x[6:10])
# df["Phone_Number"]=df["Phone_Number"].apply(lambda x: str(x))
#df["Phone_Number"]=df["Phone_Number"].apply(lambda x: x[0:3] + "-" + x[3:6] + "-" + x[6:10])
df["Phone_Number"]=df["Phone_Number"].str.replace('nan--', '')
df["Phone_Number"]=df["Phone_Number"].str.replace('Na--', '')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

# splitting Columns

In [91]:
df[["Street", "State", "Zip"]] = df["Address"].str.split(',', n=2, expand=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,state,zip,State,Zip
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",True,No,123 Shire Lane,Shire,None,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,False,Yes,93 West Main Street,None,None,None,None
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,False,NaN,298 Drugs Driveway,None,None,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",True,Y,980 Paper Avenue,Pennsylvania,18503,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,True,No,123 Dragons Road,None,None,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,True,Yes,768 City Parkway,None,None,None,None
6,1007,Jeff,Winger,,1209 South Street,False,No,1209 South Street,None,None,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,False,No,98 Clue Drive,None,None,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,True,NaN,123 Middle Earth,None,None,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",True,No,25th Main Street,New York,None,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",True,No,612 Shire Lane,Shire,None,Shire,None
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,True,NaN,2394 Hogwarts Avenue,None,None,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,True,N,2039 Main Street,None,None,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,True,No,343 City Parkway,None,None,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,False,No,214 HR Avenue,None,None,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,False,N,2395 Hogwarts Avenue,None,None,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",True,No,121 Paper Avenue,Pennsylvania,None,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,True,NaN,3498 Super Lane,None,None,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",True,N,910 Tatooine Road,Tatooine,None,Tatooine,None

# staandazdizing Column values using replacce

In [90]:
df["Paying Customer"]=df["Paying Customer"].str.replace('Yes', 'Y')
df["Paying Customer"]=df["Paying Customer"].str.replace('Falseoo', 'False')
df["Paying Customer"]=df["Paying Customer"].str.replace('N', 'False')
df["Paying Customer"]=df["Paying Customer"].str.replace('Trueeseses', 'True')
df["Paying Customer"]=df["Paying Customer"].str.replace('False/a', 'N/a')

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,state,zip,State,Zip
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",True,No,123 Shire Lane,Shire,None,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,False,Yes,93 West Main Street,None,None,None,None
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,False,NaN,298 Drugs Driveway,None,None,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",True,Y,980 Paper Avenue,Pennsylvania,18503,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,True,No,123 Dragons Road,None,None,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,True,Yes,768 City Parkway,None,None,None,None
6,1007,Jeff,Winger,,1209 South Street,False,No,1209 South Street,None,None,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,False,No,98 Clue Drive,None,None,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,True,NaN,123 Middle Earth,None,None,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",True,No,25th Main Street,New York,None,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",True,No,612 Shire Lane,Shire,None,Shire,None
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,True,NaN,2394 Hogwarts Avenue,None,None,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,True,N,2039 Main Street,None,None,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,True,No,343 City Parkway,None,None,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,False,No,214 HR Avenue,None,None,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,False,N,2395 Hogwarts Avenue,None,None,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",True,No,121 Paper Avenue,Pennsylvania,None,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,True,NaN,3498 Super Lane,None,None,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",True,N,910 Tatooine Road,Tatooine,None,Tatooine,None

# Fill Null values

# Filtering Down Rows of Data